DROP DATABASE IF EXISTS cargarImagen;
CREATE DATABASE cargarImagen;
USE cargarImagen;
CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  phone CHAR(9) NOT NULL,
  photo VARCHAR(500) UNIQUE NOT NULL
);
